### ISSUE TITLE
contrib command can't be found 

### ISSUE THREAD

**Issue by jrw95** [brightcove-archive/zencoder_contribflow#1]
I installed contribflow, and then ran npm install -g contribflow, in one of my videojs repos, but all I got was:

-bash: contrib: command not found

I tried adding the path to contrib.js to my $PATH, but that didn't help (I don't know why it would, contrib isn't an executable or a script, but I was willing to try anything).

Is there additional information that needs to go in the readme, about how to execute contrib.js?  Is it a node command of some sort?

**Comment by brandonarbini** [comment]
I believe it runs as a grunt command right now. I talked to Steve about making it a standalone binary. That's in the plan.

**Comment by heff** [comment]
Actually I got it set up to use the `contrib` command instead of grunt, and Jim was testing that. Only I didn't figure out how to update the npm version until today. The latest version is now on npm.

**Comment by jrw95** [comment]
Enhancement?  Really? :)

Anyway, I got contrib to work, or at least I got it working so that I could call contrib in a project.
