### ISSUE TITLE
Contrib throws an error creating hotfix branches

### ISSUE THREAD

**Issue by jrw95** [brightcove-archive/zencoder_contribflow#9]
STR:
1. Run contrib hotfix start
2. At the prompt for a hotfix name, enter any of the following:
    A valid hotfix number (in the contribflow-test project, 8 is a valid hotfix number)
    Any other number
    A text string
3. Hit enter.

Expected:
In all cases, a branch is created with the text supplied.

Actual:
Git thinks that you're trying to check out remotes/upstream/stable, and aborts without creating the hotfix:

``` bash
jwhisenant-retina:contribflow-test-https jwhisenant$ contrib hotfix start
prompt: Name of the hotfix:  test2
-----> Creating the stable branch based on remotes/upstream/stable
$ git checkout -b stable remotes/upstream/stable
fatal: git checkout: updating paths is incompatible with switching branches.
Did you intend to checkout 'remotes/upstream/stable' which can not be resolved as commit?
-----> Process aborted
-----> Exit status: 128
-----> You may need to run any following commands manually...
-----> Pushing the stable branch to origin
$ git push origin stable
-----> Tracking the stable branch against origin/stable
$ git branch --set-upstream stable origin/stable
-----> Updating the stable branch with upstream changes
$ git checkout stable && git pull upstream stable
-----> Creating the hotfix/test2 branch based on stable
$ git checkout -b hotfix/test2 stable
-----> Pushing the hotfix/test2 branch to origin
$ git push origin hotfix/test2
-----> Tracking the hotfix/test2 branch against origin/hotfix/test2
$ git branch --set-upstream hotfix/test2 origin/hotfix/test2
-----> Ready to start building your hotfix in branch hotfix/test2.

jwhisenant-retina:contribflow-test-https jwhisenant$ contrib hotfix start
prompt: Name of the hotfix:  8
-----> Creating the stable branch based on remotes/upstream/stable
$ git checkout -b stable remotes/upstream/stable
fatal: git checkout: updating paths is incompatible with switching branches.
Did you intend to checkout 'remotes/upstream/stable' which can not be resolved as commit?
-----> Process aborted
-----> Exit status: 128
-----> You may need to run any following commands manually...
-----> Pushing the stable branch to origin
$ git push origin stable
-----> Tracking the stable branch against origin/stable
$ git branch --set-upstream stable origin/stable
-----> Updating the stable branch with upstream changes
$ git checkout stable && git pull upstream stable
-----> Creating the hotfix/8 branch based on stable
$ git checkout -b hotfix/8 stable
-----> Pushing the hotfix/8 branch to origin
$ git push origin hotfix/8
-----> Tracking the hotfix/8 branch against origin/hotfix/8
$ git branch --set-upstream hotfix/8 origin/hotfix/8
-----> Ready to start building your hotfix in branch hotfix/8.
```

**Comment by jrw95** [comment]
This still happens, reproduced in testing today.

**Comment by jrw95** [comment]
The steps to reproduce this problem are a bit different today:
1. Go through the contribflow feature flow:
    contrib feature start:  
    name the feature, 
    make a small change to README.md, 
    commit, 
    submit, 
    delete the feature branch.
    (This is an abbreviated workflow to be sure, but it's the expected sequence of events in feature branch management.)
2. Run contrib hotfix start
3. At the prompt for a hotfix name, enter any of the following:
A valid hotfix number (in the contribflow-test project, 8 is a valid hotfix number)
Any other number
A text string
4. Hit enter.

Same results as above.

**Comment by jrw95** [comment]
Steve suggested running a `git remote update && git fetch` after the failed attempt to create the hotfix.
After doing this, I was successful creating a hotfix branch.

**Comment by heff** [comment]
I added git fetch and did some other cleanup. I believe this should be working now, but should be tested again.

**Comment by jrw95** [comment]
Retested hotfix and feature create and submit. Both worked.
For some reason, hotfix and feature delete is not working, but only with contrib.
I'm not sure why, because the logic hasn't changed from when it did work, so I'll open a separate issue.
